workspace = { members = ["r1", "r2", "r3", "s1", "s2"] }
[package]
name = "geo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
